<a href="https://colab.research.google.com/github/microdir/microdir.tech/blob/master/MLPatividade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Artificial Neural Network
# from https://www.superdatascience.com/machine-learning/ 


# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
#import tensorflow.compat.v1 as tf
#tf.disable_v2_behavior()
# Mais sobre pandas: https://github.com/Natalnet/GCiD/blob/master/Codes/Basic%20Module/01%20-%20Introdu%C3%A7%C3%A3o%20%C3%A0%20Leitura%20e%20Visualiza%C3%A7%C3%A3o%20de%20Dados.ipynb 


In [27]:
# Importing the dataset
dataset = pd.read_csv('https://raw.githubusercontent.com/ect-info/ml/master/dados/DataBaseLop.csv')

dataset.head( 10 )

Unnamed: 0     ano  ...  diferentesExerSemanas89  diferentesExerSemanas1011
0           0  2017.2  ...                     15.0                        0.0
1           1  2017.2  ...                     10.0                        0.0
2           2  2017.2  ...                      3.0                        6.0
3           3  2017.2  ...                      3.0                        0.0
4           4  2017.2  ...                      7.0                        0.0
5           5  2017.2  ...                      9.0                        0.0
6           6  2017.2  ...                      5.0                        1.0
7           7  2017.2  ...                      0.0                        6.0
8           8  2017.2  ...                      4.0                        0.0
9           9  2017.2  ...                     15.0                        0.0

[10 rows x 72 columns]

In [28]:
dataset.describe()

Unnamed: 0  ...  diferentesExerSemanas1011
count  447.000000  ...                 447.000000
mean   223.000000  ...                   2.863535
std    129.182042  ...                   5.681114
min      0.000000  ...                   0.000000
25%    111.500000  ...                   0.000000
50%    223.000000  ...                   1.000000
75%    334.500000  ...                   4.000000
max    446.000000  ...                  49.000000

[8 rows x 70 columns]

In [53]:
#notaP1 qsubAtéP1 qsubAtéP1com100% 
X = dataset.iloc[:,[2,17,20]].values
y = dataset.iloc[:, 11].values

print(X[0:6,:])

[[24. 46. 29.]
 [72. 31. 31.]
 [36.  9.  9.]
 [ 4. 16. 15.]
 [16. 20. 18.]
 [52. 24. 19.]]


In [0]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [32]:
print(X_test[0:6,:])

[[ 1.65222755  0.83729473  1.08550057]
 [-0.57781115 -0.37058302 -0.25021232]
 [ 0.73047822 -0.01532486  0.25068001]
 [ 1.40444547  0.62413983  0.91853646]
 [-1.02381888  1.19255289  1.66987496]
 [-0.08224699 -1.01004772 -0.91806877]]


In [0]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages

import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

In [0]:
# CONFIGURANDO A CAMADA DE ENTRADA COM TRÊS NEURÔNIOS, MAIS TRÊS NA CAMADA ESCONDIDA
classifier.add(Dense( activation = 'relu', input_dim = 3, units = 3, kernel_initializer = 'uniform'))


# UMA CAMADA ESCONDIDA COM SEIS NEURÔNIOS
classifier.add(Dense( activation = 'relu', units = 6, kernel_initializer = 'uniform' ))


# CAMADA DE SAÍDA - APENAS UMA SAIDA
classifier.add(Dense( activation = 'sigmoid', units = 1, kernel_initializer = 'uniform'))

In [0]:

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [70]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 5, epochs = 40)
#classifier.fit(X_train, y_train)


Epoch 1/40
357/357 [==============================] - 1s 2ms/step - loss: 0.6931 - acc: 0.4874
Epoch 2/40
357/357 [==============================] - 0s 213us/step - loss: 0.6891 - acc: 0.7339
Epoch 3/40
357/357 [==============================] - 0s 214us/step - loss: 0.6642 - acc: 0.7115
Epoch 4/40
357/357 [==============================] - 0s 222us/step - loss: 0.6093 - acc: 0.7731
Epoch 5/40
357/357 [==============================] - 0s 224us/step - loss: 0.5643 - acc: 0.8011
Epoch 6/40
357/357 [==============================] - 0s 218us/step - loss: 0.5409 - acc: 0.8123
Epoch 7/40
357/357 [==============================] - 0s 245us/step - loss: 0.5283 - acc: 0.8179
Epoch 8/40
357/357 [==============================] - 0s 227us/step - loss: 0.5183 - acc: 0.8207
Epoch 9/40
357/357 [==============================] - 0s 224us/step - loss: 0.5097 - acc: 0.8263
Epoch 10/40
357/357 [==============================] - 0s 227us/step - loss: 0.5027 - acc: 0.8263
Epoch 11/40
357/357 [==========

In [71]:
# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
print(y_pred[0:10])

y_pred = (y_pred > 0.5)
print(y_pred[0:10])

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

[[0.9701209 ]
 [0.24336025]
 [0.8508616 ]
 [0.95368093]
 [0.24336025]
 [0.46849608]
 [0.8511329 ]
 [0.30842268]
 [0.96937925]
 [0.24336025]]
[[ True]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]]


In [72]:
print("Matriz de Confusão:")
print(cm)
print("Taxa de acerto:")
print((cm[0,0]+cm[1,1])/len(y_test) )
print(len(y_test))




Matriz de Confusão:
[[33  5]
 [10 42]]
Taxa de acerto:
0.8333333333333334
90
